### ISSUE TITLE
(suggestion) Add cascade restore

### ISSUE THREAD

**Issue by YarinceP** [shiftonelabs/laravel-cascade-deletes#3]
Thanks for this great package. It would be a great feature if you could add cascade restoration.

**Comment by patrickcarlohickman** [comment]
@YarinceP I appreciate the suggestion and I'm glad you find the package useful.

Unfortunately, cascading restores would be a bit of an undertaking. The issue with cascading restores is that there is currently no way to determine which soft deleted records should actually be restored.

Say I have an order, and it has three order lines. Now, one of them was a mistake, so I delete one order line. Next, I decide I don't want the order anymore, so I delete it, and that cascades deletes the remaining two order lines. Finally, I decide I do want that order after all, so I restore it.

At this point, which order lines should be restored? We can either restore the two order lines that were deleted with the order, or we can restore all three deleted order lines associated with the order.

If you want all three order lines restored, that would be pretty easy to implement. We would probably need another property to specify which relationships should cascade restores, and the restore logic would (hopefully) be fairly simple.

However, most users would probably want only the two lines that were deleted with the order to be restored. Unfortunately, there is currently no way to determine that. We would probably need a new database field that would contain a transaction id that can be used to bind all the deleted records together.

Finally, in addition to that, with the multiple options for restoring, we'd need a way for the user to pick with restore method they want (full or most recently deleted). They would also need to be able to pick the restore method on a per-relationship basis, as well.

So, I don't think the ability is impossible, but it would be some work.

Thanks,
Patrick

**Comment by midblep** [comment]
Sorry to open this back up. I do not use this package but I came across this issue when Googling about cascading SoftDeletes in Laravel. I had an internal conversation about this problem as we use cascading SoftDeletes that potentially need to be restored in our own application. We came up with a pretty easy solution, and I want to share it here for any fellow Googlers that may be in need of help. 

You can leverage the deleted_at's timestamp to determine whether something has been deleted *after* the parent was deleted or not. It would be a simple check during restoring at most.
For example if we take that same order, the first deleted order line would be deleted before the order is deleted, but the other two get deleted by the cascade when the order gets deleted. The deleted_at timestamp of the other two lines will be after the deleted_at timestamp of the order, and so you can pick those two out when restoring the order and only restore those, whilst ignoring any order lines with a delete_at timestamp that is before the deleted_at timestamp of the order.

Now, this package deletes things before the parent is deleted and that indeed makes things a little more difficult. But if you are doing this in your own Laravel app you could simply delete the items in the ''deleted'' function instead of the ''deleting'' function.

That aside, your package has been helpful for me to discover how cascading works in Laravel. Thank you for creating this.
