### ISSUE TITLE
How to cascade to belongsToMany?

### ISSUE THREAD

**Issue by ahoiroman** [shiftonelabs/laravel-cascade-deletes#4]
Hi :-) 

I got this model:

```
<?php

namespace App;

use App\Traits\ProductTrait;
use ShiftOneLabs\LaravelCascadeDeletes\CascadesDeletes;

/**
 * Class Product
 *
 * @package App
 */
class Product extends Model
{
    use ProductTrait, CascadesDeletes;
    
    protected $cascadeDeletes = ['fields', 'productAttributes', 'category'];
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsToMany
     */
    public function productAttributes()
    {
        return $this->belongsToMany(ProductAttribute::class)
            ->withPivot($this->attributefields)->withTimestamps();
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function position()
    {
        return $this->hasOne(Position::class);
    }
    
    public function category()
    {
        return $this->hasOne(ProductCategory::class);
    }
    
}
```

Unfortunately the `productAttributes` are not being deleted. It does not throw an Error but the items are just still there in the database.

Anything I can do?

**Comment by patrickcarlohickman** [comment]
Cascading deletes on a `BelongsToMany` relationship is setup to only delete the relationship between the two items, not the items themselves. This means that only the records in the pivot table relating the two models together are deleted (your `product_product_attribute` table).

I don't know your specific business logic or intended use case, but I'm going to use your models as an example.

In your example, you have products and product attributes. With the many-to-many relationship, you're saying that a product can have many product attributes and a product attribute can have (or be on) many products. Maybe you have a master list of product attributes, and when you create a product, you can assign it multiple attributes.

When you delete a product, you don't want to actually delete the product attributes, because those attributes may be related to other products. For example, when you delete a t-shirt product that has a color product attribute, you don't want to delete the color product attribute, because that would remove it from every product in your system. When you delete a t-shirt, you only want to make sure that the records in the pivot table that relate that t-shirt to the color attribute are removed.

Hopefully this makes sense. :)

Thanks,
Patrick

**Comment by ahoiroman** [comment]
Thanks for your explanation. This helped a lot 😊
