### ISSUE TITLE
Specifying nested relations

### ISSUE THREAD

**Issue by crishoj** [shiftonelabs/laravel-cascade-deletes#7]
Would you consider accepting a pull request with support for nested relations, similar to the way nested relations can be eager-loaded with the syntax `relation.relation`?

**Comment by patrickcarlohickman** [comment]
While the nested functionality may seem similar at first glance, their responsibilities are quite different. I think we would want the responsibility to remain with the closest relative, instead of allowing distant relatives to dictate when records should be deleted.

If a PR were submitted, I'd certainly take a look to see how it is implemented and how the use case pans out, but it is not something I would plan on adding support for myself.

Thanks,
Patrick
